[2024-06-30T05:22:03.256+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-30T05:22:03.269+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: amazon_analytics_dag.tsk_transfer_s3_to_redshift manual__2024-06-30T05:21:42.604752+00:00 [queued]>
[2024-06-30T05:22:03.277+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: amazon_analytics_dag.tsk_transfer_s3_to_redshift manual__2024-06-30T05:21:42.604752+00:00 [queued]>
[2024-06-30T05:22:03.278+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-06-30T05:22:03.295+0000] {taskinstance.py:2330} INFO - Executing <Task(S3ToRedshiftOperator): tsk_transfer_s3_to_redshift> on 2024-06-30 05:21:42.604752+00:00
[2024-06-30T05:22:03.301+0000] {standard_task_runner.py:63} INFO - Started process 46061 to run task
[2024-06-30T05:22:03.305+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'amazon_analytics_dag', 'tsk_transfer_s3_to_redshift', 'manual__2024-06-30T05:21:42.604752+00:00', '--job-id', '288', '--raw', '--subdir', 'DAGS_FOLDER/amazonanalytics.py', '--cfg-path', '/tmp/tmpsa18cn7o']
[2024-06-30T05:22:03.306+0000] {standard_task_runner.py:91} INFO - Job 288: Subtask tsk_transfer_s3_to_redshift
[2024-06-30T05:22:03.350+0000] {task_command.py:426} INFO - Running <TaskInstance: amazon_analytics_dag.tsk_transfer_s3_to_redshift manual__2024-06-30T05:21:42.604752+00:00 [running]> on host ip-172-31-19-147.us-west-2.compute.internal
[2024-06-30T05:22:03.435+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='amazon_analytics_dag' AIRFLOW_CTX_TASK_ID='tsk_transfer_s3_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-06-30T05:21:42.604752+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-30T05:21:42.604752+00:00'
[2024-06-30T05:22:03.436+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-30T05:22:03.454+0000] {base.py:84} INFO - Using connection ID 'aws_s3_conn' for task execution.
[2024-06-30T05:22:03.457+0000] {base.py:84} INFO - Using connection ID 'aws_s3_conn' for task execution.
[2024-06-30T05:22:03.457+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3_conn', conn_type='aws') credentials retrieved from login and password.
[2024-06-30T05:22:03.469+0000] {s3_to_redshift.py:193} INFO - Executing COPY command...
[2024-06-30T05:22:03.471+0000] {base.py:84} INFO - Using connection ID 'conn_id_redshift' for task execution.
[2024-06-30T05:22:03.738+0000] {sql.py:487} INFO - Running statement: 
                    COPY PUBLIC.amazondata 
                    FROM 's3://cleaned-data-zone-csv-bucket5/response_data_30062024052145.csv'
                    credentials
                    'aws_access_key_id=AKIAZQ3DOUDY5ZQWQYRC;aws_secret_access_key=***'
                    
                    csv IGNOREHEADER 1;
        , parameters: None
[2024-06-30T05:22:10.601+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-30T05:22:10.602+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/providers/amazon/aws/transfers/s3_to_redshift.py", line 197, in execute
    redshift_hook.run(sql, autocommit=self.autocommit)
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 435, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/redshift_connector/cursor.py", line 248, in execute
    raise e
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/redshift_connector/cursor.py", line 241, in execute
    self._c.execute(self, operation, args)
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/redshift_connector/core.py", line 1990, in execute
    self.handle_messages(cursor)
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/redshift_connector/core.py", line 2197, in handle_messages
    raise self.error
redshift_connector.error.ProgrammingError: {'S': 'ERROR', 'C': 'XX000', 'M': "Load into table 'amazondata' failed.  Check 'stl_load_errors' system table for details.", 'F': '../src/pg/src/backend/commands/commands_copy.c', 'L': '741', 'R': 'CheckMaxRowError'}
[2024-06-30T05:22:10.607+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=amazon_analytics_dag, task_id=tsk_transfer_s3_to_redshift, run_id=manual__2024-06-30T05:21:42.604752+00:00, execution_date=20240630T052142, start_date=20240630T052203, end_date=20240630T052210
[2024-06-30T05:22:10.619+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 288 for task tsk_transfer_s3_to_redshift ({'S': 'ERROR', 'C': 'XX000', 'M': "Load into table 'amazondata' failed.  Check 'stl_load_errors' system table for details.", 'F': '../src/pg/src/backend/commands/commands_copy.c', 'L': '741', 'R': 'CheckMaxRowError'}; 46061)
[2024-06-30T05:22:10.658+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-30T05:22:10.668+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-30T05:22:10.668+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
