[2024-06-28T00:25:32.074+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T00:25:32.084+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: amazon_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-28T00:25:18.980253+00:00 [queued]>
[2024-06-28T00:25:32.090+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: amazon_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-28T00:25:18.980253+00:00 [queued]>
[2024-06-28T00:25:32.091+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-06-28T00:25:32.108+0000] {taskinstance.py:2330} INFO - Executing <Task(S3KeySensor): tsk_is_file_in_s3_available> on 2024-06-28 00:25:18.980253+00:00
[2024-06-28T00:25:32.114+0000] {standard_task_runner.py:63} INFO - Started process 34645 to run task
[2024-06-28T00:25:32.117+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'amazon_analytics_dag', 'tsk_is_file_in_s3_available', 'manual__2024-06-28T00:25:18.980253+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/amazonanalytics.py', '--cfg-path', '/tmp/tmpjyu2ygys']
[2024-06-28T00:25:32.118+0000] {standard_task_runner.py:91} INFO - Job 73: Subtask tsk_is_file_in_s3_available
[2024-06-28T00:25:32.155+0000] {task_command.py:426} INFO - Running <TaskInstance: amazon_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-28T00:25:18.980253+00:00 [running]> on host ip-172-31-19-147.us-west-2.compute.internal
[2024-06-28T00:25:32.236+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='amazon_analytics_dag' AIRFLOW_CTX_TASK_ID='tsk_is_file_in_s3_available' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T00:25:18.980253+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T00:25:18.980253+00:00'
[2024-06-28T00:25:32.236+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T00:25:32.249+0000] {baseoperator.py:400} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2024-06-28T00:25:32.249+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_28062024002521.csv
[2024-06-28T00:25:32.255+0000] {base.py:84} INFO - Using connection ID 'aws_s3_conn' for task execution.
[2024-06-28T00:25:32.255+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3_conn', conn_type='aws') credentials retrieved from login and password.
[2024-06-28T00:25:37.723+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_28062024002521.csv
[2024-06-28T00:25:37.738+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-06-28T00:25:37.738+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T00:25:37.743+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=amazon_analytics_dag, task_id=tsk_is_file_in_s3_available, run_id=manual__2024-06-28T00:25:18.980253+00:00, execution_date=20240628T002518, start_date=20240628T002532, end_date=20240628T002537
[2024-06-28T00:25:37.776+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T00:25:37.786+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T00:25:37.786+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
