[2024-06-29T23:04:48.357+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T23:04:48.368+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: amazon_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-29T23:04:36.897477+00:00 [queued]>
[2024-06-29T23:04:48.374+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: amazon_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-29T23:04:36.897477+00:00 [queued]>
[2024-06-29T23:04:48.375+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-06-29T23:04:48.391+0000] {taskinstance.py:2330} INFO - Executing <Task(S3KeySensor): tsk_is_file_in_s3_available> on 2024-06-29 23:04:36.897477+00:00
[2024-06-29T23:04:48.397+0000] {standard_task_runner.py:63} INFO - Started process 44187 to run task
[2024-06-29T23:04:48.401+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'amazon_analytics_dag', 'tsk_is_file_in_s3_available', 'manual__2024-06-29T23:04:36.897477+00:00', '--job-id', '203', '--raw', '--subdir', 'DAGS_FOLDER/amazonanalytics.py', '--cfg-path', '/tmp/tmpv4il31da']
[2024-06-29T23:04:48.402+0000] {standard_task_runner.py:91} INFO - Job 203: Subtask tsk_is_file_in_s3_available
[2024-06-29T23:04:48.443+0000] {task_command.py:426} INFO - Running <TaskInstance: amazon_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-29T23:04:36.897477+00:00 [running]> on host ip-172-31-19-147.us-west-2.compute.internal
[2024-06-29T23:04:48.532+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='amazon_analytics_dag' AIRFLOW_CTX_TASK_ID='tsk_is_file_in_s3_available' AIRFLOW_CTX_EXECUTION_DATE='2024-06-29T23:04:36.897477+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-29T23:04:36.897477+00:00'
[2024-06-29T23:04:48.533+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T23:04:48.546+0000] {baseoperator.py:400} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2024-06-29T23:04:48.546+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_29062024230439.csv
[2024-06-29T23:04:48.552+0000] {base.py:84} INFO - Using connection ID 'aws_s3_conn' for task execution.
[2024-06-29T23:04:48.553+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3_conn', conn_type='aws') credentials retrieved from login and password.
[2024-06-29T23:04:54.182+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_29062024230439.csv
[2024-06-29T23:04:59.196+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_29062024230439.csv
[2024-06-29T23:05:04.205+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_29062024230439.csv
[2024-06-29T23:05:09.217+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_29062024230439.csv
[2024-06-29T23:05:14.225+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_29062024230439.csv
[2024-06-29T23:05:19.233+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_29062024230439.csv
[2024-06-29T23:05:24.242+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_29062024230439.csv
[2024-06-29T23:05:29.253+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_29062024230439.csv
[2024-06-29T23:05:34.276+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_29062024230439.csv
[2024-06-29T23:05:39.285+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_29062024230439.csv
[2024-06-29T23:05:44.294+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_29062024230439.csv
[2024-06-29T23:05:49.302+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_29062024230439.csv
[2024-06-29T23:05:49.312+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T23:05:49.312+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 183, in execute
    super().execute(context)
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/sensors/base.py", line 281, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 60.76513702503871 seconds exceeds the specified timeout of 60.0.
[2024-06-29T23:05:49.316+0000] {taskinstance.py:1206} INFO - Immediate failure requested. Marking task as FAILED. dag_id=amazon_analytics_dag, task_id=tsk_is_file_in_s3_available, run_id=manual__2024-06-29T23:04:36.897477+00:00, execution_date=20240629T230436, start_date=20240629T230448, end_date=20240629T230549
[2024-06-29T23:05:49.329+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 203 for task tsk_is_file_in_s3_available (Sensor has timed out; run duration of 60.76513702503871 seconds exceeds the specified timeout of 60.0.; 44187)
[2024-06-29T23:05:49.362+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-29T23:05:49.380+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T23:05:49.388+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
