[2024-06-27T23:31:10.065+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T23:31:10.076+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: amazon_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-27T23:30:56.437165+00:00 [queued]>
[2024-06-27T23:31:10.082+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: amazon_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-27T23:30:56.437165+00:00 [queued]>
[2024-06-27T23:31:10.083+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-06-27T23:31:10.099+0000] {taskinstance.py:2330} INFO - Executing <Task(S3KeySensor): tsk_is_file_in_s3_available> on 2024-06-27 23:30:56.437165+00:00
[2024-06-27T23:31:10.104+0000] {standard_task_runner.py:63} INFO - Started process 33868 to run task
[2024-06-27T23:31:10.108+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'amazon_analytics_dag', 'tsk_is_file_in_s3_available', 'manual__2024-06-27T23:30:56.437165+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/amazonanalytics.py', '--cfg-path', '/tmp/tmpzhpt52rl']
[2024-06-27T23:31:10.109+0000] {standard_task_runner.py:91} INFO - Job 55: Subtask tsk_is_file_in_s3_available
[2024-06-27T23:31:10.149+0000] {task_command.py:426} INFO - Running <TaskInstance: amazon_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-27T23:30:56.437165+00:00 [running]> on host ip-172-31-19-147.us-west-2.compute.internal
[2024-06-27T23:31:10.224+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='amazon_analytics_dag' AIRFLOW_CTX_TASK_ID='tsk_is_file_in_s3_available' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T23:30:56.437165+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-27T23:30:56.437165+00:00'
[2024-06-27T23:31:10.225+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T23:31:10.238+0000] {baseoperator.py:400} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2024-06-27T23:31:10.238+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_27062024233059.csv
[2024-06-27T23:31:10.244+0000] {base.py:84} INFO - Using connection ID 'aws_s3_conn' for task execution.
[2024-06-27T23:31:10.244+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3_conn', conn_type='aws') credentials retrieved from login and password.
[2024-06-27T23:31:15.718+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_27062024233059.csv
[2024-06-27T23:31:20.730+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_27062024233059.csv
[2024-06-27T23:31:25.739+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_27062024233059.csv
[2024-06-27T23:31:30.747+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_27062024233059.csv
[2024-06-27T23:31:35.757+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_27062024233059.csv
[2024-06-27T23:31:40.767+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_27062024233059.csv
[2024-06-27T23:31:45.777+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_27062024233059.csv
[2024-06-27T23:31:50.786+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_27062024233059.csv
[2024-06-27T23:31:55.795+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_27062024233059.csv
[2024-06-27T23:32:00.803+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_27062024233059.csv
[2024-06-27T23:32:05.813+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_27062024233059.csv
[2024-06-27T23:32:10.823+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_27062024233059.csv
[2024-06-27T23:32:10.833+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T23:32:10.833+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 183, in execute
    super().execute(context)
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/sensors/base.py", line 281, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 60.59473176501342 seconds exceeds the specified timeout of 60.0.
[2024-06-27T23:32:10.837+0000] {taskinstance.py:1206} INFO - Immediate failure requested. Marking task as FAILED. dag_id=amazon_analytics_dag, task_id=tsk_is_file_in_s3_available, run_id=manual__2024-06-27T23:30:56.437165+00:00, execution_date=20240627T233056, start_date=20240627T233110, end_date=20240627T233210
[2024-06-27T23:32:10.850+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 55 for task tsk_is_file_in_s3_available (Sensor has timed out; run duration of 60.59473176501342 seconds exceeds the specified timeout of 60.0.; 33868)
[2024-06-27T23:32:10.858+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-27T23:32:10.867+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T23:32:10.868+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
