[2024-06-28T00:23:08.013+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T00:23:08.024+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: amazon_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-28T00:22:54.323691+00:00 [queued]>
[2024-06-28T00:23:08.031+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: amazon_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-28T00:22:54.323691+00:00 [queued]>
[2024-06-28T00:23:08.031+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-06-28T00:23:08.046+0000] {taskinstance.py:2330} INFO - Executing <Task(S3KeySensor): tsk_is_file_in_s3_available> on 2024-06-28 00:22:54.323691+00:00
[2024-06-28T00:23:08.052+0000] {standard_task_runner.py:63} INFO - Started process 34628 to run task
[2024-06-28T00:23:08.055+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'amazon_analytics_dag', 'tsk_is_file_in_s3_available', 'manual__2024-06-28T00:22:54.323691+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/amazonanalytics.py', '--cfg-path', '/tmp/tmplhoh1cv2']
[2024-06-28T00:23:08.057+0000] {standard_task_runner.py:91} INFO - Job 70: Subtask tsk_is_file_in_s3_available
[2024-06-28T00:23:08.094+0000] {task_command.py:426} INFO - Running <TaskInstance: amazon_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-28T00:22:54.323691+00:00 [running]> on host ip-172-31-19-147.us-west-2.compute.internal
[2024-06-28T00:23:08.174+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='amazon_analytics_dag' AIRFLOW_CTX_TASK_ID='tsk_is_file_in_s3_available' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T00:22:54.323691+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T00:22:54.323691+00:00'
[2024-06-28T00:23:08.175+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T00:23:08.187+0000] {baseoperator.py:400} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2024-06-28T00:23:08.188+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_28062024002257.csv
[2024-06-28T00:23:08.193+0000] {base.py:84} INFO - Using connection ID 'aws_s3_conn' for task execution.
[2024-06-28T00:23:08.194+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3_conn', conn_type='aws') credentials retrieved from login and password.
[2024-06-28T00:23:13.658+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_28062024002257.csv
[2024-06-28T00:23:18.666+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_28062024002257.csv
[2024-06-28T00:23:23.675+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_28062024002257.csv
[2024-06-28T00:23:28.685+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_28062024002257.csv
[2024-06-28T00:23:33.693+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_28062024002257.csv
[2024-06-28T00:23:38.704+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_28062024002257.csv
[2024-06-28T00:23:43.712+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_28062024002257.csv
[2024-06-28T00:23:48.722+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_28062024002257.csv
[2024-06-28T00:23:53.734+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_28062024002257.csv
[2024-06-28T00:23:58.742+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_28062024002257.csv
[2024-06-28T00:24:03.751+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_28062024002257.csv
[2024-06-28T00:24:08.760+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket5/response_data_28062024002257.csv
[2024-06-28T00:24:08.769+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T00:24:08.769+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 183, in execute
    super().execute(context)
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/deevar_venv/lib/python3.12/site-packages/airflow/sensors/base.py", line 281, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 60.58132478999323 seconds exceeds the specified timeout of 60.0.
[2024-06-28T00:24:08.774+0000] {taskinstance.py:1206} INFO - Immediate failure requested. Marking task as FAILED. dag_id=amazon_analytics_dag, task_id=tsk_is_file_in_s3_available, run_id=manual__2024-06-28T00:22:54.323691+00:00, execution_date=20240628T002254, start_date=20240628T002308, end_date=20240628T002408
[2024-06-28T00:24:08.786+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 70 for task tsk_is_file_in_s3_available (Sensor has timed out; run duration of 60.58132478999323 seconds exceeds the specified timeout of 60.0.; 34628)
[2024-06-28T00:24:08.830+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-28T00:24:08.839+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T00:24:08.840+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
